# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HivemapperImagery
                                 A QGIS plugin
 This plugin fetches the latest imagery from the Hivemapper network
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-24
        copyright            : (C) 2024 by Hivemapper
        email                : hi@hivemapper.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Hivemapper'
__date__ = '2024-10-24'
__copyright__ = '(C) 2024 by Hivemapper'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HivemapperImagery class from file HivemapperImagery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hivemapper_imagery import HivemapperImageryPlugin
    return HivemapperImageryPlugin(iface)
