# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HivemapperImagery
                                 A QGIS plugin
 Access to hivemapper network imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-22
        copyright            : (C) 2024 by Hivemapper Inc.
        email                : hi@hivemapper.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import subprocess
import sys

__author__ = 'Hivemapper Inc.'
__date__ = '2024-10-22'
__copyright__ = '(C) 2024 by Hivemapper Inc.'

def install_package(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HivemapperImagery class from file HivemapperImagery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    try:
        import hivemapper  # Try importing the package
    except ImportError:
        # If not installed, install it
        install_package('hivemapper-python')

    from .hivemapper_imagery import HivemapperImageryPlugin
    return HivemapperImageryPlugin()
